### ISSUE TITLE
ReferenceError: window is not defined (even after npm install canvas)

### ISSUE THREAD

**Issue by rifflesbits** [imgly/rembrandt#12]
I tried the Rembrandt sample usage in a node js hello world project after running:
`npm install canvas`

but I still get the error below:

```
ReferenceError: window is not defined
    at Function.createImage ([myProject]\node_modules\rembrandt\build\browser.js:358:10)
    at [myProject]\node_modules\rembrandt\build\browser.js:229:47
    at new Promise (<anonymous>)
    at Rembrandt._loadImage ([myProject]\node_modules\rembrandt\build\browser.js:219:15)
    at Rembrandt._loadImages ([myProject]\node_modules\rembrandt\build\browser.js:201:20)
    at Rembrandt.compare ([myProject]\node_modules\rembrandt\build\browser.js:136:20)
```

Here's the example:

```
const Rembrandt = require('rembrandt/build/browser');
const http = require('http');
const hostname = '127.0.0.1';
const port = 3000;


const server = http.createServer((req, res) => {

    const rembrandt = new Rembrandt({
        // `imageA` and `imageB` can be either Strings (file path on node.js,
        // public url on Browsers) or Buffers
        imageA: './label1.png',
        imageB: './label2.png',
      
        // Needs to be one of Rembrandt.THRESHOLD_PERCENT or Rembrandt.THRESHOLD_PIXELS
        thresholdType: Rembrandt.THRESHOLD_PERCENT,
      
        // The maximum threshold (0...1 for THRESHOLD_PERCENT, pixel count for THRESHOLD_PIXELS
        maxThreshold: 0.01,
      
        // Maximum color delta (0...1):
        maxDelta: 0.02,
      
        // Maximum surrounding pixel offset
        maxOffset: 0,
      
        renderComposition: true, // Should Rembrandt render a composition image?
        compositionMaskColor: Rembrandt.Color.RED // Color of unmatched pixels
      })


        // Run the comparison
        rembrandt.compare()
        .then(function (result) {
            console.log('Passed:', result.passed)
            console.log('Pixel Difference:', result.differences, 'Percentage Difference', result.percentageDifference, '%')
            console.log('Composition image buffer:', result.compositionImage)

            // Note that `compositionImage` is an Image when Rembrandt.js is run in the browser environment
        })

    .catch((e) => {
        console.error(e)
    })

    res.statusCode = 200;
    res.setHeader('Content-Type', 'text/plain');
    res.end('Hello World\n');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});


```

**Comment by oussla** [comment]
Hello, 
encountered the same issue, resolved by requiring the "Node" version of Rembrandt: 

`const Rembrandt = require('rembrandt/build/node');`

Then, image comparison is working great on command line whith Node. 

Tested with Rembrand v0.1.3, Node v10.15.0, on MacOSX 10.14.6.
